on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      # Disable “safe.directory” check. It is a workaround for the error:
      #   fatal: detected dubious ownership in repository at '/cygdrive/d/a/fswatch-for-Windows/fswatch-for-Windows'
      - run: git config --global --add safe.directory '*'

      - uses: actions/checkout@v4
      - uses: cygwin/cygwin-install-action@master
        with:
          packages: >-
            autobuild
            autoconf
            automake
            cmake
            gcc-g++
            gettext
            gettext-devel
            libtool
            make
            zip
      - run: bash build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: build/publish/*.zip
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: build/publish/*.zip
